replicaCount: 2

image:
  repository: docker-web
  pullPolicy: IfNotPresent
  tag: "latest"

containerPort: 5002

service:
  type: LoadBalancer
  port: 5002
  targetPort: 5002

backendApiUrl: "http://backend-service:5001/fetch_price"
