apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
      - name: backend-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: MYSQL_HOST
          value: "{{ .Values.database.host }}"
        - name: MYSQL_PORT
          value: "{{ .Values.database.port | toString }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.database.name }}"
        - name: MYSQL_USER
          value: "{{ .Values.database.credentials.user }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.database.credentials.password }}"
