apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5002
  selector:
    app: {{ .Release.Name }}-frontend
  type: {{ .Values.service.type }}
