replicaCount: 2

image:
  repository: docker-backend-service
  pullPolicy: IfNotPresent
  tag: "latest"

containerPort: 5001

service:
  name: backend-service
  type: ClusterIP
  port: 5001
  targetPort: 5001

database:
  host: "mysqldb"
  port: 3306
  name: "crypto_db"
  credentials:
    user: "appuser"
    password: "123456"
